### PR TITLE
[Breaking] Remove unused net_profile_docker_bridge_cidr

### LINKED ISSUE #122: why does the example usage use "170.10.0.1/16" for the docker bridge cidr?
The default value for this according to the aks docs is "172.17.0.1/16", https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni

Can I presume the benefit is to allow for "172.17.0.1/16" to be usable in the network?

Are there downsides to not using an RFC 1918 address here?

Thanks!

### PR DESCRIPTION
**Pull request by zioproto**
Since 2020 the default runtime is containerd and not Docker
https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2020-06-29

The setting `docker_bridge_cidr` is doing nothing.
If you check the interfaces on the AKS nodes they dont have any Docker bridge configured.

Fixes #122

### CODE REVIEW

**Comment by zioproto** [comment]
This can't be removed so easily 😭  
from the docs:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster
Screenshot 2022-07-13 at 12 35 35

**Comment by zioproto** [comment]
This PR is currently blocked by https://github.com/hashicorp/terraform-provider-azurerm/issues/18119

After the issue in the azurerm provider is closed, it is possible to finish this PR

**Comment by zioproto** [comment]
this PR should work once https://github.com/hashicorp/terraform-provider-azurerm/pull/20952 is released in the provider

**Comment by zioproto** [comment]
as per https://github.com/hashicorp/terraform-provider-azurerm/issues/18119 the provider change is available in provider version v3.49.0

**Comment by lonegunmanb** [comment]
Hi @zioproto, I think it's time to merge this pr in 7.0.0, would you please rebase your branch with the latest main branch and commit again? Thanks!

**Review by lonegunmanb — APPROVED** [review]
Thanks @zioproto, LGTM! 🚀

**Pull request merged**
