### PR TITLE
Add support for `support_plan` and `Premium` sku tier.

### PR DESCRIPTION
**Pull request by ecklm**
## Describe your changes

Make use of the premium SKU option and the support plan feature available in the azurerm provider sinve version 3.84.0.

## Issue number

#477

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [x] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by ecklm** [comment]
@microsoft-github-policy-service agree company="Alerant IT Ltd."

**Comment by lonegunmanb** [comment]
Thanks @ecklm for opening this pr! I've checked the [CHANGELOG](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md?plain=1#L386), this feature was introduced in `3.84.0`, would you please update the provider requirement in [`versions.tf`](https://github.com/Azure/terraform-azurerm-aks/blob/main/versions.tf) file too? Thanks!

**Comment by ecklm** [comment]
Sure. Done in 5d24e33.

**Comment by ecklm** [comment]
Sure. Done in c2013a2

**Review by lonegunmanb — APPROVED** [review]
Thanks @ecklm, LGTM!

**Comment by ecklm** [comment]
Can this be expected in a release soon? I see it's been a year since the last one.

**Comment by zioproto** [comment]
> Can this be expected in a release soon? I see it's been a year since the last one.

The 6.8.0 is not the latest release, for some reason GitHub is not displaying the correct information. @lonegunmanb 

@ecklm 8.0.0 is the current release, check the git tag to see the release date

**Pull request merged**
