### PR TITLE
add drain_timeout_in_minutes and node_soak_duration_in_minutes

### PR DESCRIPTION
**Pull request by zioproto**
## Describe your changes

Implements the following GA functionalities:
* Node Soak duration for upgraded: https://azure.microsoft.com/en-us/updates/generally-available-node-soak-duration-for-upgrades
* Set node drain timeout value: https://learn.microsoft.com/en-us/azure/aks/upgrade-aks-cluster?tabs=azure-cli#set-node-drain-timeout-value

Requires provider version v3.106.0
https://github.com/hashicorp/terraform-provider-azurerm/pull/26137
## Issue number

#530

## Checklist before requesting a review
- [X] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [X] I have executed pre-commit on my machine
- [X] I have passed pr-check on my machine

### CODE REVIEW

**Comment by zioproto** [comment]
When testing this PR consider all the following user reported issue with the upstream provider:

* https://github.com/Azure/terraform-azurerm-aks/issues/563
* https://github.com/Azure/terraform-azurerm-aks/issues/561
* https://github.com/Azure/terraform-azurerm-aks/issues/530
* https://github.com/Azure/terraform-azurerm-aks/issues/557

**Comment by morbendor** [comment]
Hey,

when the upcoming version of the module, which includes this changes, will be released? 

Our CI/CD pipeline is dependent on that fix.

Thank you for your assistance.

**Comment by zioproto** [comment]
> when the upcoming version of the module, which includes this changes, will be released?

Because we have added two new required fields this will be released with version v10

**Comment by morbendor** [comment]
> > when the upcoming version of the module, which includes this changes, will be released?
> 
> Because we have added two new required fields this will be released with version v10

and there is ETA for it? :)

**Comment by zioproto** [comment]
@aditya-enthu thanks for your review ! great feedback! I implemented your suggestions. Please have a look.

**Comment by morbendor** [comment]
> > when the upcoming version of the module, which includes this changes, will be released?
> 
> Because we have added two new required fields this will be released with version v10

Thank you for the update. Could you please let us know the estimated release date for version v10, which includes the new required fields?

**Comment by zioproto** [comment]
Please @lonegunmanb could you comment on the release date ? thanks

**Comment by zioproto** [comment]
The end to end version upgrade test is failing :(
https://github.com/Azure/terraform-azurerm-aks/actions/runs/9641915202/job/26588582582?pr=564#step:6:247

It seems a problem with the default value of `drain_timeout_in_minutes`:

```
~ default_node_pool {
                    name                          = "nodepool"
                    tags                          = {}
                    # (33 unchanged attributes hidden)
        
                  ~ upgrade_settings {
                      ~ drain_timeout_in_minutes      = 0 -> 30
                        # (2 unchanged attributes hidden)
                    }
                }
```

@ms-henglu @lonegunmanb do you have any suggestion on how to activate this feature without recreating the cluster ?

**Review by lonegunmanb — APPROVED** [review]
LGTM!

**Pull request merged**
