### PR TITLE
Adding the private_dns_zone_id input variable

### PR DESCRIPTION
**Pull request by fgauna12**
Fixes https://github.com/Azure/terraform-azurerm-aks/issues/120

Changes proposed in the pull request:

Added an optional input variable to accept private_dns_zone_id
First time contributing to this repo. Hopefully, this helps. The tests passed and ran terrafmt.

BTW: Sorry about the closed, duplicate, unmerged pull requests. Third time is the charm! 😄

### CODE REVIEW

**Review by liechtinat — COMMENTED** [review]
LGTM, can someone merge this?

**Review by lonegunmanb — CHANGES_REQUESTED** [review]

**Review by lonegunmanb — APPROVED** [review]
Thanks @fgauna12 , LGTM but it seems like we have some conflict due to recently upgrades. Would you please solve the conflict? Thanks!

**Review by lonegunmanb — CHANGES_REQUESTED** [review]
Thanks @fgauna12 , LGTM but it seems like we have some conflict due to recently upgrades. Would you please solve the conflict? Thanks!

**Comment by fgauna12** [comment]
@lonegunmanb - I resolved the merge conflicts before you wrote the comment. I don't see any more merge conflicts.

**Review by lonegunmanb — APPROVED** [review]
Thanks @fgauna12 , LGTM!

**Pull request merged**
