### PR TITLE
fix(typo): typo in output variable

### PR DESCRIPTION
**Pull request by mbaykara**
## Issue number

#000

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [x] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by zioproto** [comment]
Please run:
`docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:latest make pre-commit`

to auto update the README. Please follow in the README `pre-commit` and `pr-check` steps when contributing.

thanks

**Comment by mbaykara** [comment]
@microsoft-github-policy-service agree

**Comment by mbaykara** [comment]
> Please run: `docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:latest make pre-commit`
> 
> to auto update the README. Please follow in the README `pre-commit` and `pr-check` steps when contributing.
> 
Thanks, I run both checks respectively.

**Comment by zioproto** [comment]
@lonegunmanb there is a change in the output, does it need a release note in the changelog ? LGTM

**Comment by lonegunmanb** [comment]
> @lonegunmanb there is a change in the output, does it need a release note in the changelog ? LGTM

It's a change to the description so I think it's not a breaking change, we can just release it.

**Comment by mbaykara** [comment]
Is any action required from me?

**Comment by lonegunmanb** [comment]
@mbaykara thanks for asking, yes, we've just fixed the failed examples so would you please rebase your pr with the latest main branch? Thanks a lot!

**Comment by mbaykara** [comment]
@lonegunmanb done with rerun `pre-commit` and `pr-check`.

**Comment by lonegunmanb** [comment]
Thanks @mbaykara , LGTM!

**Pull request merged**
