### PR TITLE
Add support for default node pool's `node_taints`

### PR DESCRIPTION
**Pull request by lonegunmanb**
## Describe your changes

This pr added support for `default_node_pool.node_taints` argument.

## Issue number

#299 

## Checklist before requesting a review
- [ ] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by mloskot** [comment]
Shouldn't the default be `[]` instead of `null`? See https://github.com/Azure/terraform-azurerm-aks/issues/85

I'm observing the following plan changes (Terraform 1.3.7, hashicorp/azurerm v3.43.0):

```
Note: Objects have changed outside of Terraform
...
        name                    = "nplin1"
        node_count              = 2
      + node_taints             = []
        tags                    = {
      ...
```

**Comment by lonegunmanb** [comment]
Thanks for asking @mloskot, for this argument I've checked the [schema definition](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_nodepool.go#L166-L173) in AzureRM provider:

```go
"node_taints": {
						Type:     pluginsdk.TypeList,
						ForceNew: true,
						Optional: true,
						Elem: &pluginsdk.Schema{
							Type: pluginsdk.TypeString,
						},
					},
```

`Optional: true` means the default value for this argument is `null`. As for the change you've seen in the plan, you can export the tfplan as json and check whether if there's any action generated for that change, as I've done in our [test framework](https://github.com/Azure/terraform-module-test-helper/blob/main/upgradetest.go#L132-L160). If there's no action then we don't need to worry about it.

**Comment by mloskot** [comment]
@lonegunmanb Thanks for the explanation and suggestions. I'll try it out.

**Review by jiaweitao001 — APPROVED** [review]
🚢

**Pull request merged**
