### PR TITLE
Possibility to setup multiple node pools

### PR DESCRIPTION
**Pull request by Sanverik**
Changes proposed in the pull request:
- extend functionality to be able to specify multiple node pools within the module

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Thanks @Sanverik for opening this PR! My personal opinion this module will focus on Aks cluster itself. The caller might attach multiple node pools with different configurations to one Aks cluster so I prefer a standalone module for the node pool.

**Comment by nlamirault** [comment]
@lonegunmanb @Sanverik what about transform this PR using a submodule of the AKS module ?

**Comment by Sanverik** [comment]
For me it looks natural to have an option to specify multiple node pool within AKS module by using my way of doing it

**Comment by lonegunmanb** [comment]
@Sanverik Thanks for opening this pr, I'm closing it because I'd like to keep this module focused on Kubernetes cluster itself.

**Pull request closed without merging**
