### PR TITLE
Remove deprecated variable `enable_kube_dashboard`

### PR DESCRIPTION
**Pull request by lonegunmanb**
This pr remove deprecated variable `enable_kube_dashboard` as #181 described. It also updated the readme file.

This pr rely on pr #188 since the removed `addon_block` will block the test code.

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Hi @davidkarlsen , I'll submit some prs, would you please give them code review before merge? Thanks!

**Comment by davidkarlsen** [comment]
> Hi @davidkarlsen , I'll submit some prs, would you please give them code review before merge? Thanks!

Sure, I'm no maintainer, but I can have a look.

**Review by davidkarlsen — APPROVED** [review]
lgtm

**Comment by zioproto** [comment]
LGTM

**Pull request merged**
