### PR TITLE
Include node_resource_group as variable

### PR DESCRIPTION
**Pull request by afym**
This PR close https://github.com/Azure/terraform-azurerm-aks/issues/135

### CODE REVIEW

**Review by sbl-matter — APPROVED** [review]
must needed change

**Comment by andypanix** [comment]
It would also be useful for us to have this PR approved, we are using this module in a context where we have resource group name constrainments and not being able to customise it is a bit problematic.

**Comment by RobMokkink** [comment]
Like @andypanix said, please merge this feature, otherwise we have a messed up naming convention.

**Comment by kebarb** [comment]
Hey reviewers folks, can this be approved ?

**Comment by shurik-io** [comment]
Hi @sbl-matter  You agreed that the change is needed. Can you please approve again, or add someone with the right permissions to do so, as you're assigned as reviewer and the PR can finally be merged. We would really appreciate it. Thanks in advance.

**Comment by sbl-matter** [comment]
Sorry @shurik-io, i reviewed, as I think you could do to, thinking that would speed up the process but apparently only somebody with write access can do anything.

**Review by sbl-matter — APPROVED** [review]
This merge would me much appreciated

**Comment by shurik-io** [comment]
> but apparently only somebody with write access can do anything.

@sbl-matter can you ping someone with write access to have a look and approve it, as I don't know who could do it. Thanks in advance.

**Comment by sbl-matter** [comment]
@lonegunmanb 
Hi, any chance you'd look into this ?

**Review by wrkode — APPROVED** [review]

**Review by wrkode — APPROVED** [review]

**Comment by eyenx** [comment]
Can this be merged? :)

**Comment by RobMokkink** [comment]
Can this be picked up as well? Thanks

**Comment by wrkode** [comment]
Yes, please waiting for this to be merged

**Review by hairmare — APPROVED** [review]

**Review by kebarb — APPROVED** [review]

**Review by lonegunmanb — APPROVED** [review]

**Comment by andypanix** [comment]
@lonegunmanb thanks for merging the PR, it would be great now if a new release would be available, could you publish the 4.15.0 release?

Many thanks!

**Comment by lonegunmanb** [comment]
Hi @andypanix , this feature has been released as 4.15.0.

**Pull request merged**
