### PR TITLE
fix: allow orchestrator_version if auto-upgrade is 'patch' to allow default_node_pool upgrade

### PR DESCRIPTION
**Pull request by aescrob**
## Describe your changes

```
-  # - patch, but then the kubernetes_version must not specify a patch number and orchestrator_version must be null
+  # - patch, but then neither the kubernetes_version nor orchestrator_version must specify a patch number
```

## Issue number

#301 

## Checklist before requesting a review
- [X] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [X] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Review by the-technat — APPROVED** [review]
LGTM

**Review by lonegunmanb — CHANGES_REQUESTED** [review]
Almost LGTM if the e2e test could pass, but would you please update `var.automatic_channel_upgrade`'s `description` about this new requirement for `orchestrator_version` when `var.automatic_channel_upgrade` = `patch`? Thanks @aescrob

**Review by lonegunmanb — CHANGES_REQUESTED** [review]
Thanks @aescrob for updating this pr, we have some e2e tests failed, one example is:

```text
TestExamplesStartup 2023-02-16T02:25:55Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Resource precondition failed
│ 
│   on ../../main.tf line 296, in resource "azurerm_kubernetes_cluster" "main":
│  296:       condition     = local.automatic_channel_upgrade_check
│     ├────────────────
│     │ local.automatic_channel_upgrade_check is false
│ 
│ Either disable automatic upgrades, or only specify up to the minor version
│ when using `automatic_channel_upgrade=patch` or don't specify
│ `kubernetes_version` at all when using
│ `automatic_channel_upgrade=stable|rapid|node-image`. With automatic
│ upgrades `orchestrator_version` must be set to `null`.
╵}
=== CONT  TestExamplesStartup
    apply.go:34: 
        	Error Trace:	/src/test/e2e/apply.go:34
        	            				/src/test/e2e/e2etest.go:57
        	            				/src/test/e2e/e2etest.go:38
        	            				/src/test/e2e/terraform_aks_test.go:22
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: Resource precondition failed
        	            	│ 
        	            	│   on ../../main.tf line 296, in resource "azurerm_kubernetes_cluster" "main":
        	            	│  296:       condition     = local.automatic_channel_upgrade_check
        	            	│     ├────────────────
        	            	│     │ local.automatic_channel_upgrade_check is false
        	            	│ 
        	            	│ Either disable automatic upgrades, or only specify up to the minor version
        	            	│ when using `automatic_channel_upgrade=patch` or don't specify
        	            	│ `kubernetes_version` at all when using
        	            	│ `automatic_channel_upgrade=stable|rapid|node-image`. With automatic
        	            	│ upgrades `orchestrator_version` must be set to `null`.
        	            	╵}
        	Test:       	TestExamplesStartup
```

Would you please fix our examples and tests, then verifiy it by [run e2e tests](https://github.com/Azure/terraform-azurerm-aks#pre-commit--pr-check--test) or just run `terraform plan` for all examples before you commit? Thanks for your understanding!

**Comment by aescrob** [comment]
Hi @lonegunmanb - thanks for your support.
I've changed the precondition to still allow orchestrator_version==null. Like this it is not a breaking change and the examples are not required to be fixed.

**Review by lonegunmanb — APPROVED** [review]
LGTM but I'd like to ask @the-technat for a review.

**Review by the-technat — APPROVED** [review]
Makes sense to me and looks good. Maybe it's worth documenting that the `orchestrator_version` can be set to `null` because it should be a non-breaking change and not because it's a recommended approach to configure the module.

**Review by lonegunmanb — APPROVED** [review]
Thanks @aescrob, LGTM! 🚀

**Pull request merged**
