### PR TITLE
export addon_profile attributes

### PR DESCRIPTION
**Pull request by davidkarlsen**
Export the addon_profile attributes in order to make these consumable by other resources.

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Hi @davidkarlsen , thanks for your pr! I've just leave a comment on your code, would you please change a little to make the module caller easier to use this output? Thanks!

**Comment by davidkarlsen** [comment]
> Hi @davidkarlsen , thanks for your pr! I've just leave a comment on your code, would you please change a little to make the module caller easier to use this output? Thanks!

Sorry for the late response - didn't notice it. I can't see any comment? Maybe you forgot to submit the review?

**Comment by lonegunmanb** [comment]
> > Hi @davidkarlsen , thanks for your pr! I've just leave a comment on your code, would you please change a little to make the module caller easier to use this output? Thanks!
> 
> Sorry for the late response - didn't notice it. I can't see any comment? Maybe you forgot to submit the review?

Hi @davidkarlsen , sorry for my fault. Would you please take a look?

**Comment by davidkarlsen** [comment]
@lonegunmanb fixed. Maybe needs some length check and defaulting to null?

**Comment by lonegunmanb** [comment]
> @lonegunmanb fixed. Maybe needs some length check and defaulting to null?

@davidkarlsen Great idea! Should we use `try` function?

**Comment by davidkarlsen** [comment]
@lonegunmanb fixed

**Comment by davidkarlsen** [comment]
@lonegunmanb what about https://github.com/Azure/terraform-azurerm-aks/pull/157 - can it be merged soon too? It's painful to lag so much on the provider version.

**Comment by davidkarlsen** [comment]
@lonegunmanb ping

**Comment by davidkarlsen** [comment]
@lonegunmanb ?

**Review by lonegunmanb — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@lonegunmanb can you do a release too?

**Comment by lonegunmanb** [comment]
@davidkarlsen #133 is nearly complete, can we wait for 1-2 days at most to see whether we can include this pr into our next release too? Thanks for your patience!

**Comment by lonegunmanb** [comment]
@davidkarlsen 4.16.0 has been released.

**Pull request merged**
