### PR TITLE
Let the users decide whether adding a random suffix in cluster and pool's name or not.

### PR DESCRIPTION
**Pull request by lonegunmanb**
As [#389](https://github.com/Azure/terraform-azurerm-aks/issues/389#issuecomment-1670748181) described, now `azurerm_kubernetes_cluster.main` has been set to `create_before_destroy = true` implicity because an `azurerm_kubernetes_cluster_node_pool` with `create_before_destroy = true` referred it, this meta argument config has been propagated to the aks resource.

We also have #491 complaining that they don't want a random suffix in node pool's name. We added `create_before_destroy = true` to the node pool resource in #357 since we'd like to create a new replacement pool before we destroy the old one so all running pods on the old pool could be evicted to the new one before the worker node have been destroyed, so the cluster's operator could avoid downtime when they have to recreate the node pool.

We respect that the users should have the right to decide the style they'd adapted already, so this pr replicated a new `azurerm_kubernetes_cluster_node_pool`, and added `create_before_destroy` in `var.node_pools` object definition.

Setting this `create_before_destroy` to `true`, nothing would happen, your node pool would still be created and managed in the old way, with a random name suffix.

Setting this `create_before_destroy` to `false`, the node pool in brown field would be destroyed and recreated in new address, without random name suffix, and when Terraform have to recreate this node pool, you must delete the old pool and create the new replacement pool with a different name. To avoid downtime we encourage the operators to create the replacement pool first, then destroy the old one.

We also added a new variable `cluster_name_random_suffix`, setting this variable to `true` would add a random suffix to cluster's name when you're creating an Aks instance in greenfield, but will do nothing to the instances in brownfield. With this random suffix now Terraform could recreate the Aks instance directly without any naming conflict.

@zioproto @TechieNat @tdevopsottawa WDYT?

## Issue number

#000

## Checklist before requesting a review
- [ ] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by zioproto** [comment]
I believe you meant to tag @the-technat ☝️

**Review by the-technat — APPROVED** [review]
It's a prone to errors doing it that way, but that should certainly give the user the flexibility to do it the way he wants.

Thanks @lonegunmanb for coding this!

**Review by zioproto — COMMENTED** [review]
It works. I tested like this:

```
locals {
  node_pools = {
    user = {
      name                = "user"
      vm_size             = var.agents_size
      enable_auto_scaling = true
      node_count          = null
      min_count           = 1
      max_count           = 3
      vnet_subnet_id      = lookup(module.network.vnet_subnets_name_id, "aks")
    },
    ingress = {
      name                = "ingress"
      vm_size             = var.agents_size
      enable_auto_scaling = false
      node_count          = 2
      vnet_subnet_id      = lookup(module.network.vnet_subnets_name_id, "aks")
      node_taints         = ["node-role.kubernetes.io/ingress=true:NoSchedule"]
    },
    spot = {
      name                = "spot"
      vm_size             = var.agents_size
      enable_auto_scaling = true
      node_count          = null
      min_count           = 1
      max_count           = 10
      vnet_subnet_id      = lookup(module.network.vnet_subnets_name_id, "aks")
      eviction_policy     = "Delete"
      spot_max_price      = 0.1
      priority            = "Spot"
      node_taints         = ["kubernetes.azure.com/scalesetpriority=spot:NoSchedule"]
      node_labels         = { "kubernetes.azure.com/scalesetpriority" = "spot" }
      zones               = ["1", "2", "3"]
      create_before_destroy = false

    },
  }
}
```

**Review by zioproto — APPROVED** [review]

**Comment by zioproto** [comment]
@lonegunmanb please have a look at the minor comments I left on the PR. It is good to merge

**Pull request merged**
