### PR TITLE
Output Kubernetes Cluster Network Profile

### PR DESCRIPTION
**Pull request by joshua-giumelli-deltatre**
## Describe your changes

Small PR to output the `network_profile` attribute of the `azurerm_kubernetes_cluster` resource.

This is so that it is easier to discover the public IP address associated with the cluster's load balancer, e.g. to follow examples from the Azure Terraform provider like [this](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/examples/kubernetes/public-ip/main.tf#L48-L51).

## Issue number

#000

## Checklist before requesting a review
- [ ] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Hi @joshua-giumelli-deltatre thanks for opening this pr! We have a CI pipeline for this repo, would you please run the following command on your side to update readme file? Thanks:

```bash
docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:latest make pre-commit
```

For Windows:

```bash
docker run --rm -v ${pwd}:/src -w /src mcr.microsoft.com/azterraform:latest make pre-commit
```

**Comment by lonegunmanb** [comment]
Hi @joshua-giumelli-deltatre thanks for the update, all have been settled down and we're good to go, the only thing I'd have to ask you to do us a favor is please read policy bot's [comment](https://github.com/Azure/terraform-azurerm-aks/pull/333#issuecomment-1481982177) and sign the agreement, thanks!

**Comment by joshua-giumelli-deltatre** [comment]
@microsoft-github-policy-service agree company="Deltatre"

**Comment by joshua-giumelli-deltatre** [comment]
Apologies for the hold up @lonegunmanb, is there anything more that needs to happen before this can be merged?

**Comment by lonegunmanb** [comment]
> Apologies for the hold up @lonegunmanb, is there anything more that needs to happen before this can be merged?

No worries @joshua-giumelli-deltatre, we'll release this feature in our next release, but the next release would be 7.0.0 and it would be a major version with some breaking changes. If you're eager to use this feature ASAP and don't want to take any risk, I think I can release a patch version for this pr first. WDYT?

**Pull request merged**
