### PR TITLE
Add `v4` sub-folder so this module could run with AzureRM provider both `v3` and `v4`.

### PR DESCRIPTION
**Pull request by lonegunmanb**
## Describe your changes

This pr added `v4` sub-folder and referenced all `.tf` files via symbolic link, and patch resources by adding Terraform override files, so the users who'd like to use AzureRM `v4` could do it by setting module's `source` to `Azure/aks/azurerm//v4`.

## Issue number

#000

## Checklist before requesting a review
- [ ] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by Glaaj** [comment]
Is this one on the radar? I'm waiting for this module to be ready for V4 so that I can leverage the options V4 has to offer like `service endpoints` on a vnet..

**Comment by johnknutsonhc** [comment]
Anything we can do to help move this along? We'd like to update our azurerm provider to 4.x

**Comment by philippeckelintive** [comment]
The [failed action](https://github.com/Azure/terraform-azurerm-aks/actions/runs/11025683706?pr=594) clearly states the problem:

> end to end / acc-tests
> The job running on runner GitHub Actions 784 has exceeded the maximum execution time of 360 minutes.

6 hours is [GitHub's usage limit](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits).

I'd guess splitting up the test into smaller chunks should solve this.

**Comment by zioproto** [comment]
Hello all,

if you have a urgent need to move to azurerm v4,
my suggestion is to look into this new Microsoft AKS resource module, that is part of the [AVM initiative](https://aka.ms/avm):

https://github.com/Azure/terraform-azurerm-avm-res-containerservice-managedcluster/

This module is guaranteed to be V4 by the end of January 2025.

For the current `terraform-azurerm-aks` module, we don't have a clear plan for the upgrade.
We might come up with some instructions to migrate to the AVM module, but there is nothing decided yet.

Cc: @ibersanoMS @nellyk @lonegunmanb

**Comment by lonegunmanb** [comment]
> The [failed action](https://github.com/Azure/terraform-azurerm-aks/actions/runs/11025683706?pr=594) clearly states the problem:
> 
> > end to end / acc-tests
> > The job running on runner GitHub Actions 784 has exceeded the maximum execution time of 360 minutes.
> 
> 6 hours is [GitHub's usage limit](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits).
> 
> I'd guess splitting up the test into smaller chunks should solve this.

Thanks a lot @philippeckelintive for this comment. I'll try to solve this issue.

**Pull request merged**
