### PR TITLE
Fixed disabling oms-plugin

### PR DESCRIPTION
**Pull request by DOboznyi**
Signed-off-by: Dmytro Oboznyi <dmytro.oboznyi@syncier.com>

If you try to disable log-analytics in existing cluster with enabled oms plugin you will get such error:
```
Error: waiting for update of Managed Kubernetes Cluster "<cluster_name>" (Resource Group "<rg_name>"): Code="GetLogAnalyticsWorkspaceError" Message="Unable to get log analytics workspace info. Resource ID: /subscriptions/<subscription_id>/resourcegroups/<rg_name>/providers/microsoft.operationalinsights/workspaces/<log_analytics_workspace_id>. Details: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.OperationalInsights/workspaces/<log_analytics_workspace_id>' under resource group '<rg_name>' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\". For more details about how to create and use log analytics workspace,  please refer to: https://aka.ms/new-log-analytics"
```

According to the official [docs](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-optout#create-template) in order to disable oms plugin its section shouldn't be removed completely. We should change enabled from `true` to `false` and put in workspace id `null` value. In such way you will not get an issue.

Changes proposed in the pull request:

- Changed addon profiles from dynamic fields to static
- Changed default value for `enable_kube_dashboard` from `null` to `false`

### CODE REVIEW

**Comment by ArgonQQ** [comment]
I can verify that this was an issue and the fix worked.

**Comment by GoozeyX** [comment]
I can confirm this is an issue and the PR resolved the issues

**Comment by jamo4ever** [comment]
Thanks for the fix @DOboznyi

**Comment by yupwei68** [comment]
Hi @DOboznyi, thanks for your contribution! 🚀  I could reproduce this problem. Would you change https://github.com/Azure/terraform-azurerm-aks/blob/master/test/fixture/main.tf#L33-L34 `kubernetes_version` and `orchestrator_version` into `1.19.6` to pass the CI test? Though it's not related to your changes, but `1.19.3` is not supported any more for `eastus`. After that, this PR will be good to me.

**Comment by DOboznyi** [comment]
> 1.19.3

Done, review please

**Review by yupwei68 — APPROVED** [review]
LGTM!

**Pull request merged**
