### PR TITLE
variablize disk size

### PR DESCRIPTION
**Pull request by sblack4**

### CODE REVIEW

**Comment by sblack4** [comment]
You're still testing on terraform v11?

**Comment by n01d** [comment]
Thank you for your contributions. I reached out internally again to find a maintainer for the project. Thank you for your patience.

**Comment by yupwei68** [comment]
Hi @sblack4 , thanks for opening this PR. 🚀 . Would you mind updating your code to merge the latest code?

**Comment by yupwei68** [comment]
Thanks for opening this PR. This has been released in 4.1.0

**Pull request closed without merging**
