### PR TITLE
Add support for private cluster API access.

### PR DESCRIPTION
**Pull request by es1o**
Hello, this is my first PR for this project. I've started using this module recently to manage my AKS cluster in my infrastructure.

I've added new variable because I'd like to restrict cluster access from internet in my infrastructure.

This change doesn't broke module behaviour because default is `false`. Default AKS cluster installation exposes API over internet as before.

Please let me know how do you think about this change.

### CODE REVIEW

**Comment by yupwei68** [comment]
Hi @es1o  Thanks for contribution. Would you mind adding this feature the test in test/fixture and in the example in README?

**Comment by es1o** [comment]
@yupwei68 Ok, I'll add. :)

**Comment by es1o** [comment]
@yupwei68 I added new variable to example.

I decided to not write tests because it requires to spawn new cluster. I didn't add any new logic, only pass variable to terraform aks resource as is. What do you think?

**Comment by yupwei68** [comment]
@es1o , you don't have to add new cluster. You can just add one field in test module "aks". Thus, I can integrate this enhancement into CI to test if it works with this field in module "aks",  and if it works without this field ("aks-without-monitor"), and to avoid being broken by following changes.

**Comment by es1o** [comment]
@yupwei68 Done, I've added to tests.

**Review by yupwei68 — APPROVED** [review]
LGTM!

**Pull request merged**
