### PR TITLE
new parameter: api_server_authorized_ip_ranges

### PR DESCRIPTION
**Pull request by madejusz**
Fixes #000 

Changes proposed in the pull request:

### CODE REVIEW

**Review by yupwei68 — COMMENTED** [review]
Thanks for your contribution! 🚀  Please add this feature into the test in test/fixture to integrate the test CI and add this feature in example in README.

**Comment by anatoliykv** [comment]
Give us this update, please! It's quite important. Thank you!

**Comment by yupwei68** [comment]
Hi @anatoliykv Please add this feature into test/fixture to integrate this feature into CI/CD test (Please ensure it runs successfully in the test) and add this feature into example in README to show an example to our users on how to use?

**Comment by fplantinga-guida** [comment]
@anatoliykv @yupwei68 Any updates on this?

**Review by nickvth — APPROVED** [review]

**Review by nickvth — CHANGES_REQUESTED** [review]
Please fix merge conflicts and other discussions

**Comment by lonegunmanb** [comment]
I'm closing this pr since we've implemented this feature in #220.

**Pull request closed without merging**
